# Generated by Django 2.0.1 on 2018-02-01 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=20)),
                ('item_id', models.IntegerField(default=0)),
                ('score', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 2, 1, 10, 27, 20, 719867))),
                ('age', models.CharField(default='no date', max_length=10)),
            ],
        ),
    ]
