# Generated by Django 2.0.1 on 2018-02-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_post',
            name='pub_date',
        ),
    ]
