# Generated by Django 2.0.1 on 2018-02-06 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180206_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteobject',
            name='site_items',
        ),
        migrations.AddField(
            model_name='siteobject',
            name='site_items',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.NewPost'),
        ),
    ]
