# Generated by Django 2.0.1 on 2018-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180206_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteobject',
            name='site_items',
        ),
        migrations.AddField(
            model_name='siteobject',
            name='site_items',
            field=models.ManyToManyField(null=True, to='news.NewPost'),
        ),
    ]
