# Generated by Django 2.0.1 on 2018-02-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.CharField(max_length=20),
        ),
    ]
