# Generated by Django 2.0.1 on 2018-02-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180201_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='age',
        ),
    ]
