# Generated by Django 2.0.1 on 2018-02-01 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 9, 3, 43, 174518)),
        ),
    ]
