# Generated by Django 2.0.1 on 2018-02-01 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180201_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 10, 27, 20, 733966)),
        ),
    ]
